export const dataSets = {
  letters: {
    name: "Letters",
    pairs: [
      { upper: "A", lower: "a" },
      { upper: "B", lower: "b" },
      { upper: "C", lower: "c" },
      { upper: "D", lower: "d" },
      { upper: "E", lower: "e" },
      { upper: "F", lower: "f" },
      { upper: "G", lower: "g" },
      { upper: "H", lower: "h" },
      { upper: "I", lower: "i" },
      { upper: "J", lower: "j" },
      { upper: "K", lower: "k" },
      { upper: "L", lower: "l" },
      { upper: "M", lower: "m" },
      { upper: "N", lower: "n" },
      { upper: "O", lower: "o" },
      { upper: "P", lower: "p" },
      { upper: "Q", lower: "q" },
      { upper: "R", lower: "r" },
      { upper: "S", lower: "s" },
      { upper: "T", lower: "t" },
      { upper: "U", lower: "u" },
      { upper: "V", lower: "v" },
      { upper: "W", lower: "w" },
      { upper: "X", lower: "x" },
      { upper: "Y", lower: "y" },
      { upper: "Z", lower: "z" },
    ],
  },
  words: {
    name: "Words",
    pairs: [
      { upper: "Cat", lower: "חתול" },
      { upper: "Dog", lower: "כלב" },
      { upper: "House", lower: "בית" },
      { upper: "Sun", lower: "שמש" },
      { upper: "Moon", lower: "ירח" },
      { upper: "Star", lower: "כוכב" },
      { upper: "Water", lower: "מים" },
      { upper: "Fire", lower: "אש" },
      { upper: "Tree", lower: "עץ" },
      { upper: "Flower", lower: "פרח" },
      { upper: "Man", lower: "איש" },
      { upper: "On", lower: "על" },
      { upper: "In", lower: "ב" },
      { upper: "Bag", lower: "תיק" },
      { upper: "Banana", lower: "בננה" },
      { upper: "Bed", lower: "מיטה" },
      { upper: "Lemon", lower: "לימון" },
      { upper: "Big", lower: "גדול" },
      { upper: "Egg", lower: "ביצה" },
      { upper: "Fat", lower: "שמן" },
      { upper: "Mouse", lower: "עכבר" },
      { upper: "Pan", lower: "מחבת" },
      { upper: "Pen", lower: "עט" },
      { upper: "Elephant", lower: "פיל" },
      { upper: "Run", lower: "לרוץ" },
      { upper: "Sad", lower: "עצוב" },
      { upper: "Hat", lower: "כובע" },
      { upper: "Small", lower: "קטן" },
      { upper: "Hen", lower: "תרנגולת" },
      { upper: "Igloo", lower: "איגלו" },
    ],
  },
  colors: {
    name: "Colors",
    pairs: [
      { upper: "Black", lower: "שחור", color: "black" },
      { upper: "Blue", lower: "כחול", color: "blue" },
      { upper: "Brown", lower: "חום", color: "brown" },
      { upper: "Green", lower: "ירוק", color: "green" },
      { upper: "Orange", lower: "כתום", color: "orange" },
      { upper: "Pink", lower: "ורוד", color: "pink" },
      { upper: "Purple", lower: "סגול", color: "purple" },
      { upper: "Red", lower: "אדום", color: "red" },
      { upper: "White", lower: "לבן", color: "white" },
      { upper: "Yellow", lower: "צהוב", color: "yellow" },
    ],
  },
  numbers: {
    name: "Numbers",
    pairs: [
      { upper: "1", lower: "one" },
      { upper: "2", lower: "two" },
      { upper: "3", lower: "three" },
      { upper: "4", lower: "four" },
      { upper: "5", lower: "five" },
      { upper: "6", lower: "six" },
      { upper: "7", lower: "seven" },
      { upper: "8", lower: "eight" },
      { upper: "9", lower: "nine" },
      { upper: "10", lower: "ten" },
      { upper: "11", lower: "eleven" },
      { upper: "12", lower: "twelve" },
      { upper: "13", lower: "thirteen" },
      { upper: "14", lower: "fourteen" },
      { upper: "15", lower: "fifteen" },
      { upper: "16", lower: "sixteen" },
      { upper: "17", lower: "seventeen" },
      { upper: "18", lower: "eighteen" },
      { upper: "19", lower: "nineteen" },
      { upper: "20", lower: "twenty" },
      { upper: "21", lower: "twenty-one" },
      { upper: "22", lower: "twenty-two" },
      { upper: "23", lower: "twenty-three" },
      { upper: "24", lower: "twenty-four" },
      { upper: "25", lower: "twenty-five" },
      { upper: "26", lower: "twenty-six" },
      { upper: "27", lower: "twenty-seven" },
      { upper: "28", lower: "twenty-eight" },
      { upper: "29", lower: "twenty-nine" },
      { upper: "30", lower: "thirty" },
    ],
  },
};
